#!/bin/bash

# Проверка запуска скрипта с правами администратора
if [ "$EUID" -ne 0 ]; then
    echo "Ошибка: запустите скрипт с правами администратора"
    echo "Перезапуск скрипта с правами администратора..."
    sudo bash "$0" "$@"
    exit $?
fi

# Переменные для часто используемых значений и команд
SUDO="sudo"
CPUFREQ_SET="cpufreq-set -r -g"
CPUFREQ_INFO="cpufreq-info -o"

# Обновление пакетов
$SUDO apt-get update

# Функция для включения максимальной производительности
function enable_max_performance() {
    # Установка пакета cpufrequtils
    $SUDO apt-get install cpufrequtils -y

    # Установка производительности на максимум
    $SUDO $CPUFREQ_SET performance

    # Зафиксировать настройки после перезагрузки
    $SUDO systemctl enable cpufrequtils
    echo "Максимальная производительность включена"
}

# Функция для выключения максимальной производительности
function disable_max_performance() {
    # Возвращение производительности в исходное состояние
    $SUDO $CPUFREQ_SET ondemand

    # Удаление настроек из файла rc.local
    $SUDO systemctl disable cpufrequtils
    echo "Максимальная производительность выключена"
}

# Функция для вывода текущего состояния производительности
function show_current_performance() {
    # Вывод текущего состояния производительности процессора
    echo "Текущее состояние производительности:"
    $SUDO $CPUFREQ_INFO
}

# Цикл для вывода списка опций
PS3="Выберите опцию: "
options=("Включить максимальную производительность" "Выключить максимальную производительность" "Показать текущее состояние производительности" "Выход")
select opt in "${options[@]}"
do
    case $opt in
        "Включить максимальную производительность")
            enable_max_performance
            ;;
        "Выключить максимальную производительность")
            disable_max_performance
            ;;
        "Показать текущее состояние производительности")
            show_current_performance
            ;;
        "Выход")
            break
            ;;
        *) echo "Некорректный выбор";;
    esac
done

exit 0
