#!/bin/bash

# Function for unpacking a deb package
unpack_deb() {
    read -p "Enter the name of the deb package: " pname
    read -p "Enter the name of the folder: " folder_name
    dpkg-deb -x "${pname}.deb" "${folder_name}"
    dpkg-deb -e "${pname}.deb" "${folder_name}/DEBIAN"
    echo "Deb package unpacked."
}

# Function for packing a deb package
pack_deb() {
    read -p "Enter the name of the folder: " folder_name
    read -p "Enter the name of the deb package: " pname
    dpkg-deb -b "${folder_name}" "${pname}.deb"
    echo "Deb package packed."
}

# Function for building a deb package
build_deb() {
    # Check for necessary components
    if ! [ -x "$(command -v equivs)" ] || ! [ -x "$(command -v devscripts)" ]; then
        echo "Necessary components are not installed. Do you want to install them now? (y/n)"
        read -p "Enter y or n: " install_choice
        if [ "$install_choice" == "y" ]; then
            sudo apt install equivs devscripts --no-install-recommends
        else
            echo "Necessary components are not installed. Operation aborted."
            return 1
        fi
    fi

    # Build deb package
    mk-build-deps -i -t "apt-get --yes" -r
    dpkg-buildpackage -b -uc -us
    echo "Deb package built."
}

# Main script code
echo "Choose an action:"
echo "1. Unpack deb"
echo "2. Pack deb"
echo "3. Build deb"
read -p "Enter the action number: " action

case $action in
  1) unpack_deb ;;
  2) pack_deb ;;
  3) build_deb ;;
  *) echo "Incorrect action choice." ;;
esac
