#!/bin/bash

echo "What do you want to create?"
echo "1. New folder"
echo "2. New text file"
echo "3. New Bash script"
echo "4. New Markdown file"
echo "5. New HTML file"

read -p "Enter your choice [1, 2, 3, 4, or 5]: " choice

case $choice in
  1)
    read -p "Enter folder name: " foldername
    mkdir "$foldername"
    echo "New folder '$foldername' created!"
    ;;
  2)
    read -p "Enter file name: " filename
    touch "$filename".txt
    echo "New text file '$filename.txt' created!"
    ;;
  3)
    read -p "Enter script name: " scriptname
    touch "$scriptname".sh
    echo "#!/bin/bash" > "$scriptname".sh
    chmod +x "$scriptname".sh
    echo "New Bash script '$scriptname.sh' created!"
    ;;
  4)
    read -p "Enter file name: " mdname
    touch "$mdname".md
    echo "New Markdown file '$mdname.md' created!"
    ;;
  5)
    read -p "Enter file name: " htmlname
    touch "$htmlname".html
    echo "<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

</body>
</html>" > "$htmlname".html
    echo "New HTML file '$htmlname.html' created!"
    ;;
  *)
    echo "Invalid choice. Please choose 1, 2, 3, 4, or 5."
    ;;
esaс
