#!/bin/bash

function install_jekyll {
  # Устанавливаем необходимые пакеты и Jekyll
  sudo apt-get update && sudo apt-get install -y ruby-full build-essential zlib1g-dev && sudo gem install jekyll bundler

  echo "Jekyll успешно установлен"
}

function new_site {
  read -p "Введите название сайта: " site_name
  jekyll new $site_name

  echo "Сайт $site_name успешно создан"
}

function start_server {
  cd $(ls -d */) # переходим в каталог созданного сайта
  bundle install # устанавливаем необходимые зависимости
  bundle exec jekyll serve

  if [ $? -ne 0 ]; then
    # Если сервер Jekyll не запущен из-за ошибки, попытаемся исправить ее
    echo "Ошибка: сервер Jekyll не запущен"
    echo "Попытка исправить ошибку..."

    # Устанавливаем необходимые зависимости и запускаем снова
    bundle update
    bundle exec jekyll serve

    if [ $? -ne 0 ]; then
      # Если ошибка не исправлена, выводим сообщение об ошибке
      echo "Ошибка: не удалось исправить ошибку"
      exit 1
    fi
  fi

  echo "Jekyll сервер успешно запущен на http://localhost:4000/"
}

function new_post {
  # Запрашиваем название поста
  read -p "Введите название нового сообщения: " post_title

  # Создаем новый файл поста с заданным именем и текущей датой
  post_date=$(date +%Y-%m-%d)
  post_filename="_posts/${post_date}-${post_title// /-}.md"

  # Создаем файл с шаблоном поста
  echo "---" > $post_filename
  echo "layout: post" >> $post_filename
  echo "title: \"$post_title\"" >> $post_filename
  echo "date: $post_date" >> $post_filename
  echo "categories: [category]" >> $post_filename
  echo "---" >> $post_filename

  echo "Новое сообщение \"$post_title\" успешно создано в блоге"
}

echo "Выберите действие:"
echo "1. Установить Jekyll"
echo "2. Создать новый сайт Jekyll"
echo "3. Запустить локальный сервер Jekyll"
echo "4. Создать новое сообщение в блоге"
read -p "Введите номер действия: " action

case $action in
  1)
    install_jekyll
    ;;
  2)
    new_site
    ;;
  3)
    start_server
    ;;
  4)
    new
