#!/bin/bash
sudo apt update
sudo apt upgrade -y --no-install-recommends
sudo apt full-upgrade -y --no-install-recommends
sudo apt install -y software-properties-common 
sudo add-apt-repository -y ppa:philip.scott/pantheon-tweaks
sudo apt update
sudo apt install -y pantheon-tweaks
