#!/bin/bash
sudo bash -c 'echo "$(logname) ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'
sudo apt update
sudo apt full-upgrade -y

wget -qO- https://git.io/papirus-icon-theme-install | sh

wget https://telegram.org/dl/desktop/linux
sudo tar xJf linux -C /opt/
sudo ln -s /opt/Telegram/Telegram /usr/local/bin/telegram-desktop

sudo dpkg --add-architecture i386 
sudo mkdir -pm755 /etc/apt/keyrings
sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/bullseye/winehq-bullseye.sources

wget -c "https://github.com/Castro-Fidel/PortWINE/raw/master/portwine_install_script/PortProton_1.0" && sh PortProton_1.0
