#!/bin/bash
sudo bash -c 'echo "$(logname) ALL=(ALL:ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'
sudo apt update
sudo apt full-upgrade -y
sudo add-apt-repository ppa:papirus/papirus
sudo apt-get update
sudo apt-get install papirus-icon-theme
sudo apt install curl
curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
sudo apt install git -y
wget https://telegram.org/dl/desktop/linux
sudo tar xJf linux -C /opt/
sudo ln -s /opt/Telegram/Telegram /usr/local/bin/telegram-desktop
