#!/bin/bash

# Create the directory for storing keyrings if it doesn't already exist
sudo install -d -m 0755 /etc/apt/keyrings

# Download the Mozilla repository signing key and save it
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null

# Import the key and verify its fingerprint
gpg -n -q --import --import-options import-show /etc/apt/keyrings/packages.mozilla.org.asc | awk '/pub/{getline; gsub(/^ +| +$/,""); if($0 == "35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3") print "\nThe key fingerprint matches ("$0").\n"; else print "\nVerification failed: the fingerprint ("$0") does not match the expected one.\n"}'

# Add the Mozilla repository to the sources list
echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null

# Create a preferences file to prioritize packages from the Mozilla repository
echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | sudo tee /etc/apt/preferences.d/mozilla

# Create a preferences file to block the installation of the snap version of Firefox
echo 'Package: firefox*
Pin: release o=Ubuntu*
Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/firefox-no-snap

# Block the installation of snapd to prevent snap version of Firefox
echo 'Package: snapd
Pin: release a=*
Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/nosnap.pref

# Update the package list and install Firefox
sudo apt-get update && sudo apt-get install -y firefox
