#!/bin/bash

# Define variables
APP_NAME=$(grep -m1 -oP "set\s*\(\s*PROJECT_NAME\s+\K[^)]+" CMakeLists.txt)
APP_VERSION=$(grep -m1 -oP "set\s*\(\s*PROJECT_VERSION\s+\K[^)]+" CMakeLists.txt)

# Check if build tools and dependencies are installed and install if necessary
if ! command -v cmake &> /dev/null || ! command -v make &> /dev/null || ! command -v qtchooser &> /dev/null; then
    echo "Installing build tools and dependencies..."
    sudo apt-get update
    sudo apt-get install -y cmake build-essential qt5-default
fi

# Create build directory, configure build with CMake, and build the application
mkdir -p build && cd build && cmake .. && make

# Create AppDir and necessary directories
mkdir -p AppDir/usr/bin AppDir/usr/lib \
    AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/256x256/apps

# Copy executable to AppDir
cp -v $APP_NAME AppDir/usr/bin

# Find dependencies and copy necessary libraries to AppDir
APP_LIBS=$(ldd $APP_NAME | awk 'BEGIN{ORS=" "}$1~/^\//{print $1}$3~/^\//{print $3}' | sed 's/,$/\n/')
cp -v $APP_LIBS AppDir/usr/lib/

# Find and copy icon to AppDir
ICON_FILE=$(find . -name "icon.png" -o -name "$APP_NAME.png" | head -n 1)
if [ -n "$ICON_FILE" ]; then
    cp -v "$ICON_FILE" "AppDir/usr/share/icons/hicolor/256x256/apps/$APP_NAME.png"
fi

# Create .desktop file
cat > AppDir/usr/share/applications/$APP_NAME.desktop << EOF
[Desktop Entry]
Name=$APP_NAME
Version=$APP_VERSION
Exec=$APP_NAME
Icon=$APP_NAME
Terminal=false
Type=Application
Categories=Utility
EOF

# Create AppImage using appimagetool
wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage -n AppDir -u "gh-releases-zsync|my-username|my-repo|latest|$APP_NAME-$APP_VERSION.AppImage.zsync" --appimage-extract-and-run

# Cleanup
rm -rf build
rm -rf AppDir
